### ISSUE TITLE
Should we consider 301 status as OK?

### ISSUE THREAD

**Issue by thom4parisot** [gaurav-nelson/asciidoc-link-check#17]
I a document I checked, several links were detected as errors:

```
[✖] https://npmjs.com/faye-websocket#
[✖] https://npmjs.com/socket.io#
```

Although when I used `curl --head` to inspect them, they are fine except they redirect, several times.

```bash
$ curl --head -L https://npmjs.com/watchify
HTTP/2 301
location: https://www.npmjs.com/watchify
...

HTTP/2 302
location: /package/watchify
...

HTTP/2 200
...
```

Should they be marked as OK?

**Comment by gaurav-nelson** [comment]
@oncletom Thank you for submitting this issue. Yes it should be marked as `OK`. I'll take this up soon.

**Comment by TimMoore** [comment]
Personally, I like detecting redirects so that the link can be updated to the new location. Maybe it could be an option.

**Comment by gaurav-nelson** [comment]
@oncletom I think this one is fixed in the latest version and I am unable to replicate this. Can you please check if this is still an issue?

**Comment by thom4parisot** [comment]
I tested the latest version published on npm and it worked as expected.

Problem solved! Thank you :-)
