### ISSUE TITLE
Add support for URL ignore list

### ISSUE THREAD

**Issue by jboxman** [gaurav-nelson/asciidoc-link-check#18]
It would be helpful to be able to specify a list of URL parts to ignore, such as example.com and 192. I'm working with a huge doc set, hundreds of files, and we have these and others scattered about.

**Comment by gaurav-nelson** [comment]
PS: https://github.com/gaurav-nelson/asciidoc-link-check#ignore-specific-links

**Comment by jboxman** [comment]
@gaurav-nelson thank you! I've only just had time to get back to this. So far it's working well.
