### ISSUE TITLE
Ignore URLs that aren't actually AsciiDoc links

### ISSUE THREAD

**Issue by jboxman** [gaurav-nelson/asciidoc-link-check#20]
I'm getting a lot of false positives on URLs that are included as part of configuration files, such as:

```
----
<VirtualHost *:80>
  DocumentRoot /var/www/html
  RewriteEngine              On
  RewriteRule     ^(.*)$     https://%{HTTP_HOST}$1 [R,L]
</VirtualHost>
----
```

and

```
[source,yaml]
----
    gitProxy:<5>
      httpProxy: http://gitproxy.com
      httpsProxy: https://gitproxy.com
      noProxy: internalgit.com
----
```

and

```
//https://kubernetes-v1-4.github.io/docs/user-guide/pod-states/
Once bound to a node, a Pod will never be bound to another node. This means that a controller is necessary in order for a Pod to survive node failure:
```

Is it possible to ignore URLs that aren't in an AsciiDoc `link` directive?

Thanks.

**Comment by gaurav-nelson** [comment]
Yes, that makes sense. Thanks for submitting this @jboxman 
Currently, the link extractor parses through the complete file and pick up URLs based on patterns matching. But using a hyperlink without the `link:` directive is also acceptable in AsciiDoc. I'll look into this issue over the weekend.

**Comment by gaurav-nelson** [comment]
I wonder why I never got back to it. Can you please check if this can be handled by using ignore patterns? (https://github.com/gaurav-nelson/asciidoc-link-check#ignore-specific-links)

**Comment by jboxman** [comment]
@gaurav-nelson, yes, that approach also works.

**Comment by gaurav-nelson** [comment]
I am closing this issue for now, if you still feel that this should be handled in some other way, feel free to open it again. 👍
