### ISSUE TITLE
`config.json` file having no effect at all 

### ISSUE THREAD

**Issue by jmbruel** [gaurav-nelson/asciidoc-link-check#28]
Trying to run: `asciidoc-link-check test.adoc -c config.json` on very basic examples, nothing works...

### test.adoc:
```
= Test

Here is a https://www.google.xorg[test].
```

### config.json
```
{
    "ignorePatterns": [
        { "pattern": "^https://www" }
    ]
}
```

**Comment by jmbruel** [comment]
<img width="185" alt="Capture d’écran 2021-02-10 à 14 18 48" src="https://user-images.githubusercontent.com/572349/107515129-e9705e80-6baa-11eb-8a16-92801a41e8f2.png">

**Comment by gaurav-nelson** [comment]
Thanks @jmbruel I confirm this isn't working. I'll check.
